# app
pack:
  name: com.example
  author: xiaozhong
  apiPath: ./api/src/main/java
  baseController: com.example.controller.base.BaseController
  tables:
    - evection_monthly
    - evection_detail
  test: foo


# spring
server:
  port: 9105
spring:
  profiles:
    active: test
  application:
    name: spring-api-seed
  datasource:
    platform: MYSQL
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useSSL=false
    username: test
    password: 1234Abcd!
  zipkin:
    locator:
      discovery:
        enabled: true


# jsonwebtoken
jwt:
  header: Authorization
  secret: SGXgvJ92pf
  expiration: 8640  # 100 days
  token-head: "Bearer "
  route:
    auth:
      path: /login
      refresh: /refresh
      register: /register


# mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml     # mapper xml 文件所在路径
  type-aliases-package: com.example.entity  # 实体所在的包, 多个包可以用逗号或者分号分隔
  #type-enums-package: com.example.entity.enums  # 自定义枚举所在包

  global-config:
    id-type: 0                # 主键类型 0:数据库ID自增, 1:用户输入ID, 2:全局唯一ID(数字类型唯一ID), 3:全局唯一ID(UUID)
    field-strategy: 2         # 字段验证策略 0:忽略判断, 1:非NULL判断, 2:非空判断
    db-column-underline: true # 表名、字段名、是否使用下划线命名
    refresh-mapper: true      # 刷新mapper方便调试

    # 逻辑删除配置 https://github.com/baomidou/mybatis-plus-doc/blob/master/logic-delete.md
    #logic-delete-value: 0    # 逻辑删除全局值
    #logic-not-delete-value: 1 # 逻辑未删除全局值
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector  # 逻辑删除SQL注入器

    #key-generator: com.baomidou.springboot.xxx        # 表关键字key生成器
    #meta-object-handler: com.baomidou.springboot.xxx  # 元对象字段填充控制器

  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启控制台日志


# actuator
management:
  security:
    enabled: false
